### ISSUE TITLE
AppVeyor fails due to a problem with the windowsservercore image

### ISSUE THREAD

**Issue by carlitorendon** [StefanScherer/docker-cli-builder#10]
`Build started
git clone -q https://github.com/StefanScherer/docker-cli-builder.git C:\projects\docker-cli-builder
git fetch -q origin +refs/pull/9/merge:
git checkout -qf FETCH_HEAD
docker build -t docker-cli-builder .
Sending build context to Docker daemon  113.2kB
Step 1/16 : FROM microsoft/windowsservercore
docker : manifest for microsoft/windowsservercore:latest not found
At line:1 char:1
+ docker build -t docker-cli-builder .
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (manifest for mi...atest not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: manifest for microsoft/windowsservercore:latest not found`

**Comment by StefanScherer** [comment]
Oh yes, the `microsoft/windowsservercore` image has no latest tag, maybe AppVeyor got it for convenience reasons.
https://hub.docker.com/_/microsoft-windows-servercore
It should use tag `ltsc2019`.

**Comment by carlitorendon** [comment]
After kind guidance by @StefanScherer, this issue was clarified. Pull request #9 went through well in AppVeyor. Now it seems new artifacts could be generated. Closing this issue.
