### ISSUE TITLE
Add Windows ARM64 build

### ISSUE THREAD

**Issue by awakecoding** [StefanScherer/docker-cli-builder#11]
I have no idea if it would build out of the box, but if you have the right Visual Studio tools to target ARM64, then it should be possible to give it a shot.

My goal would be to see how difficult it would be to use the Docker CLI on a Surface Pro X, with the Docker Engine running elsewhere.

The real Docker host could be Windows Server 2019 or Linux, but I am also curious to give it a shot with the recent ACI integration.

This being said, I could try using an x86 build of the Docker CLI with the emulation available on ARM64.

**Comment by StefanScherer** [comment]
Hi @awakecoding 
Thanks for your interest in ARM64 binaries :-)

Docker CLI is written in Golang, so a Visual Studio doesn't help here. There is no official Golang for Windows ARM64 yet, but they're working on it.

What I can suggest is to look into WSL 2 where you can run Linux binaries. AFAIK WSL 2 is available on Windows ARM64 devices. What you then need is a linux ARM64 Docker CLI which you can find as static binary at https://download.docker.com/linux/static/stable/aarch64 or install it through the Linux package manager.

**Comment by StefanScherer** [comment]
Here is the upstream golang issue to track progress https://github.com/golang/go/issues/36439
I‘m closing this for now.
