### ISSUE TITLE
Keep Chocolatey package updated

### ISSUE THREAD

**Issue by w5l** [StefanScherer/docker-cli-builder#17]
Current version of this project published to [Chocolatey is `19.03.12`](https://community.chocolatey.org/packages/docker-cli). Current version according to this repository is `20.10.9`.

There are some posts on the Choco package itself asking for updates as well.

I'm unsure what you have set up in AppVeyor beyond the build script in this repository. If there is no automated push to the Chocolatey repo, it would be quite easy to set up a GitHub action which triggers on release. If you want, I can help you set this up.

**Comment by StefanScherer** [comment]
There is a new choco package for 20.10.12 which uses the upstream binaries. 🎉
I‘ll stop building binaries, the CI is broken. 😬
