### ISSUE TITLE
Binaries available from Docker

### ISSUE THREAD

**Issue by davaya** [StefanScherer/docker-cli-builder#18]
Docker is apparently distributing `docker` and `dockerd` binaries on the downlow without advertising their existence.  Currently up to version 20.10.14:  https://download.docker.com/win/static/stable/x86_64/

**Comment by StefanScherer** [comment]
Thanks @davaya , Yes I know (I work at Docker 😅). So there's no need to compile it with this repo. The chocolatey package also has been updated.

**Comment by davaya** [comment]
Perhaps you could put in a plug for your employer to make them visible on the downloads page.  I'm probably not alone in having an employer-provided VDI without Administrator privileges.  People have come up with all sorts of ridiculous workarounds (such as installing WSL2, which requires hyper-v, which is not usable in a VDI even with Admin) because they are apparently unaware that the `docker` binary already exists.   So much wasted effort, so easily avoided.

**Comment by echosalik** [comment]
Just to add, the binary from the above link does not have compose or buildx. Is there any way to include it?
