### ISSUE TITLE
Upload as nuget package

### ISSUE THREAD

**Issue by Roemer** [StefanScherer/docker-cli-builder#6]
Are there any plans to create a NuGet package out of the Docker-CLI executable? That way it would be easier to use in for example Cake Build.

**Comment by StefanScherer** [comment]
I haven‘t planned that. 
Could you explain why this would be easier?
How would that look like?
What advantage would that be to have only the Docker CLI compared to have eg. Docker Desktop installed?

**Comment by Roemer** [comment]
Yes sure, here is my scenario:
I have a Jenkins that uses dynamic Windows build agents in a Docker Swarm to build/test .net projects. For that I have custom Docker Images with .netcore and such.
In addition, I have Cake Build that contains the logic that the build agent executes.
One of the things I run in the build agent are Integration tests. As they need a database, the docker agent spins up a new database (also in Docker Swarm in a Linux node), runs the tests and then disposes the database from the swarm.
The build agent spins up the new database in the swarm by using the local docker cli with the `-H <swarm manager>` parameter to execute the docker commands on the remote docker.

So in that scenario, all I need is the docker cli in the build agent. I could also integrate the chocolatey version of it on the build agent Docker Image directly but I would more prefer to install/download what is needed on the fly via cake build. For that, it would be much easier to just have it as a NuGet package which can then be added as addin in cake and used as a normal tool (or for example with Cake.Docker).

Right now, I just manually download the file from github inside my cake task before spinning up the database Swarm Service:
```csharp
DownloadFile("https://github.com/StefanScherer/docker-cli-builder/releases/download/19.03.3/docker.exe", File("./docker.exe"));
```
and override the Tools location for Cake.Docker:
```csharp
var settings = new DockerCustomCommandSettings {
    ToolPath = File("./docker.exe")
};
```

Hope that clears it up a bit.

**Comment by StefanScherer** [comment]
Thanks, I understand.
Setting up a nuget package is out of the scope of this repo. Others could use the GitHub releases and build (and maintain) a nuget package. :-)

**Comment by Roemer** [comment]
Ok no problem. I created a package and a package builder. The package is at https://www.nuget.org/packages/docker-cli and the builder script at https://github.com/Roemer/nuget-packages (where I also maintain other packages).
