### ISSUE TITLE
Docker build using Docker Cli on windows 

### ISSUE THREAD

**Issue by sasanknvs** [StefanScherer/docker-cli-builder#8]
I am using this cli tool on windows to connect to docker daemon hosted on a linux system. I am facing issue while running "docker build" against my Dockerfile created for a dotnet core project. And it fails at the step where it will restore the nuget packages. Not sure what is the reason. 
Below is the error.
/usr/share/dotnet/sdk/2.1.807/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. 

/usr/share/dotnet/sdk/2.1.807/NuGet.targets(123,5): error :   No such device or address 

But the same works perfectly fine when I login to the Dockerhost and try to run it from there .

Could you please help me here ? Will docker cli tool for windows does not support all the commands or any special configuration to be done ? Note that I am using ssh connection to connect from docker-cli to docker host.

**Comment by StefanScherer** [comment]
I'm not aware of missing features in the CLI.
But going through SSH from Windows requires an SSH Client, I don't know how good it will play together with Docker.
